//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gogin203Ekz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naim_Opis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Naim_Opis()
        {
            this.Sklad = new HashSet<Sklad>();
        }
    
        public string Cod_tovara { get; set; }
        public string Naimenovanie { get; set; }
        public string Proizvod { get; set; }
        public string Postav { get; set; }
        public string Cat_tovara { get; set; }
        public string Opisanie { get; set; }
        public string Izobr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad> Sklad { get; set; }
    }
}
