//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gogin203Ekz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzov
    {
        public int cod_Pol { get; set; }
        public string Familia { get; set; }
        public string Ima_Otchestvo { get; set; }
        public string Pochta { get; set; }
        public string Parol { get; set; }
        public Nullable<int> kod_rol { get; set; }
    
        public virtual rol rol { get; set; }
    }
}
