//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gogin203Ekz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdGoginEntities2 : DbContext
    {
        private static BdGoginEntities2 gogcontext;
        public BdGoginEntities2()
            : base("name=BdGoginEntities2")
        {
        }
        public static BdGoginEntities2 getcontect()
        {
            if (gogcontext == null)
                gogcontext = new BdGoginEntities2();
            return gogcontext;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Naim_Opis> Naim_Opis { get; set; }
        public virtual DbSet<Polzov> Polzov { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
    }
}
